// Ações referente a criação de conta
export const SIGNUP = "SIGNUP";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// Ações referentes ao login
export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

// Country Actions
export const COUNTRY_OPEN = "COUNTRY_OPEN";
export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_OPEN_SUCCESS = "COUNTRY_OPEN_SUCCESS";
export const COUNTRY_OPEN_FAILED = "COUNTRY_OPEN_FAILED";

export const COUNTRY_ADD = "COUNTRY_ADD";
export const COUNTRY_ADD_SUCCESS = "COUNTRY_ADD_SUCCESS";
export const COUNTRY_ADD_FAILED = "COUNTRY_ADD_FAILED";

export const COUNTRY_EDIT_OPEN = "COUNTRY_EDIT_OPEN";
export const COUNTRY_EDIT_OPEN_SUCCESS = "COUNTRY_EDIT_OPEN_SUCCESS";
export const COUNTRY_EDIT_OPEN_FAILED = "COUNTRY_EDIT_OPEN_FAILED";

export const COUNTRY_EDIT_SAVE = "COUNTRY_EDIT_SAVE";
export const COUNTRY_EDIT_SAVE_SUCCESS = "COUNTRY_EDIT_SAVE_SUCCESS";
export const COUNTRY_EDIT_SAVE_FAILED = "COUNTRY_EDIT_SAVE_FAILED";

export const COUNTRY_DEL = "COUNTRY_DEL";
export const COUNTRY_DEL_SUCCESS = "COUNTRY_DEL_SUCCESS";
export const COUNTRY_DEL_FAILED = "COUNTRY_DEL_FAILED";

export const ERASE_COUNTRY = "ERASE_COUNTRY";

// Team Actions
export const TEAM_OPEN = "TEAM_OPEN";
export const TEAM_LOADING = "TEAM_LOADING";
export const TEAM_OPEN_SUCCESS = "TEAM_OPEN_SUCCESS";
export const TEAM_OPEN_FAILED = "TEAM_OPEN_FAILED";

export const TEAM_ADD = "TEAM_ADD";
export const TEAM_ADD_SUCCESS = "TEAM_ADD_SUCCESS";
export const TEAM_ADD_FAILED = "TEAM_ADD_FAILED";

export const TEAM_DEL = "TEAM_DEL";
export const TEAM_DEL_SUCCESS = "TEAM_DEL_SUCCESS";
export const TEAM_DEL_FAILED = "TEAM_DEL_FAILED";

export const TEAM_EDIT_OPEN = "TEAM_EDIT_OPEN";
export const TEAM_EDIT_OPEN_SUCCESS = "TEAM_EDIT_OPEN_SUCCESS";
export const TEAM_EDIT_OPEN_FAILED = "TEAM_EDIT_OPEN_FAILED";

export const TEAM_EDIT_SAVE = "TEAM_EDIT_SAVE";
export const TEAM_EDIT_SAVE_SUCCESS = "TEAM_EDIT_SAVE_SUCCESS";
export const TEAM_EDIT_SAVE_FAILED = "TEAM_EDIT_SAVE_FAILED";

export const ERASE_TEAM = "ERASE_TEAM";

// Match Actions
export const MATCH_OPEN = "MATCH_OPEN";
export const MATCH_LOADING = "MATCH_LOADING";
export const MATCH_OPEN_SUCCESS = "MATCH_OPEN_SUCCESS";
export const MATCH_OPEN_FAILED = "MATCH_OPEN_FAILED";

export const MATCH_ADD = "MATCH_ADD";
export const MATCH_ADD_SUCCESS = "MATCH_ADD_SUCCESS";
export const MATCH_ADD_FAILED = "MATCH_ADD_FAILED";

export const MATCH_EDIT_OPEN = "MATCH_EDIT_OPEN";
export const MATCH_EDIT_OPEN_SUCCESS = "MATCH_EDIT_OPEN_SUCCESS";
export const MATCH_EDIT_OPEN_FAILED = "MATCH_EDIT_OPEN_FAILED";

export const MATCH_EDIT_SAVE = "MATCH_EDIT_SAVE";
export const MATCH_EDIT_SAVE_SUCCESS = "MATCH_EDIT_SAVE_SUCCESS";
export const MATCH_EDIT_SAVE_FAILED = "MATCH_EDIT_SAVE_FAILED";

export const MATCH_DEL = "MATCH_DEL";
export const MATCH_DEL_SUCCESS = "MATCH_DEL_SUCCESS";
export const MATCH_DEL_FAILED = "MATCH_DEL_FAILED";

export const MATCH_FIN = "MATCH_FIN";
export const MATCH_FIN_SUCCESS = "MATCH_FIN_SUCCESS";
export const MATCH_FIN_FAILED = "MATCH_FIN_FAILED";

export const ERASE_MATCH = "ERASE_MATCH";

// Bet Actions
export const BET_OPEN = "BET_OPEN";
export const BET_LOADING = "BET_LOADING";
export const BET_OPEN_SUCCESS = "BET_OPEN_SUCCESS";
export const BET_OPEN_FAILED = "BET_OPEN_FAILED";

export const BET_ADD = "BET_ADD";
export const BET_ADD_SUCCESS = "BET_ADD_SUCCESS";
export const BET_ADD_FAILED = "BET_ADD_FAILED";

export const ERASE_BET = "ERASE_BET";
